spring.datasource.url=jdbc:postgresql://dpg-d57qnq95pdvs738dk04g-a.singapore-postgres.render.com/moneymanager_nx7l
spring.datasource.username=moneymanager_nx7l_user
spring.datasource.password=B1Vbp7BsqrBbdvU9YuypZ8k9Ic0zlw4T